name: 1 - Continuous Integration
run-name: "${{ github.workflow }}"

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  REGISTRY: ${{ vars.REGISTRY }}
  MLFLOW_TRACKING_URI: ${{ vars.MLFLOW_TRACKING_URI }}
  MLFLOW_EXPERIMENT_NAME: ${{ vars.MLFLOW_EXPERIMENT_NAME }}
  MLFLOW_MODEL_NAME: ${{ vars.MLFLOW_MODEL_NAME }}

  BASE_URL: https://d37ci6vzurychx.cloudfront.net/trip-data
  TRAIN_DATA: 2011,2012
  VALIDATION_DATA: 2013
  SEED: 42
  TEST_SIZE: 0.2

  MODEL_PATH: artifacts/model.pkl

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.13' }
      - run: pip install uv
      - run: uv sync --dev
      - run: uv run pytest tests/test_api.py -v
      - run: uv run pytest tests/test_train.py -v
  
  build-images:
    runs-on: ubuntu-latest
    needs: test-unit
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build training image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/training/Dockerfile
          platforms: linux/amd64
          push: false
          tags: training:${{ github.sha }}
          outputs: type=docker,dest=/tmp/training.tar
      - run: docker load --input /tmp/training.tar

      - name: Build serving image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/serving/Dockerfile
          platforms: linux/amd64
          push: false
          tags: serving:${{ github.sha }}
          outputs: type=docker,dest=/tmp/serving.tar
      - run: docker load --input /tmp/serving.tar

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push training image
        run: |
          docker tag training:${{ github.sha }} ${{ env.REGISTRY }}/${{ github.repository }}/src/training:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ github.repository }}/src/training:${{ github.sha }}

      - name: Push serving staging image
        run: |
          docker tag serving:${{ github.sha }} ${{ env.REGISTRY }}/${{ github.repository }}/src/serving:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ github.repository }}/src/serving:${{ github.sha }}