name: 2 - Continuous Delivery
run-name: "${{ github.workflow }}"

on:
  workflow_run:
    workflows: ["1 - Continuous Integration"]
    types: [completed]
  workflow_dispatch:

jobs:
  train-and-build:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training (gera artifacts/model.pkl)
        env:
          MLFLOW_TRACKING_URI: ${{ vars.MLFLOW_TRACKING_URI }}
        run: python -m src.train

      - name: Build serving image
        run: docker build -t taxi-serving:staging .

      - name: Save image as artifact
        run: docker save taxi-serving:staging -o taxi-serving-staging.tar

      - name: Upload serving image artifact
        uses: actions/upload-artifact@v4
        with:
          name: serving-image-staging
          path: taxi-serving-staging.tar
